name: Sync Backend to Hugging Face

on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push Subdirectory to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Configure temporary git identity
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # 2. Add the Hugging Face remote
          git remote add hf https://geemal204:$HF_TOKEN@huggingface.co/spaces/geemal204/driveease

          # 3. Split out the backend folder into its own local temporary branch
          git subtree split --prefix=driveease-backend -b temp-backend-branch

          # 4. FORCE push that isolated local branch into HF's main branch
          git push hf temp-backend-branch:main --force
